exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex.raw('SET foreign_key_checks = 0;')
    .then(() => {
      return knex('question').del()
        .then(function () {
          return knex('question').insert([
            { id: 1, title: '', type: 'Behavioral', level: 0, question: 'Elaborate how you solved an every day problem.' },
            { id: 2, title: '', type: 'Behavioral', level: 0, question: 'What is your greatest strength?' },
            { id: 3, title: '', type: 'Behavioral', level: 0, question: 'What is your greatest weakness?' },
            { id: 4, title: '', type: 'Behavioral', level: 0, question: 'What makes a person smart?' },
            { id: 5, title: '', type: 'Behavioral', level: 0, question: 'Explain to me what programming is.' },
            { id: 6, title: '', type: 'Behavioral', level: 0, question: 'Have you ever considered giving up because something felt too difficult to do?' },
            { id: 7, title: '', type: 'Behavioral', level: 0, question: 'What is your biggest fear and how have you overcome it?' },
            { id: 8, title: '', type: 'Behavioral', level: 0, question: 'What was the most uncomfortable situation you have ever been in and why?' },
            { id: 9, title: '', type: 'Behavioral', level: 0, question: 'What would you do if two people in your team just do not get along?' },
            { id: 10, title: '', type: 'Behavioral', level: 0, question: 'What vocational failure in your life has affected you the most?' },
            { id: 11, title: '', type: 'Algorithm', level: 0, question: 'How would you verify a prime number? Code your answer and return a boolean' },
            { id: 12, title: '', type: 'Algorithm', level: 0, question: 'Reverse a string.' },
            { id: 13, title: '', type: 'Algorithm', level: 0, question: 'Given an array of numbers, return an array with roman numbers.' },
            { id: 14, title: '', type: 'Algorithm', level: 1, question: 'How would you reverse words in a sentence?' },
            { id: 15, title: '', type: 'Algorithm', level: 1, question: 'How would you swap two numbers without using a temporary variable?' },
            { id: 16, title: '', type: 'Algorithm', level: 1, question: 'How would you remove duplicate members from an array?' },
            { id: 17, title: '', type: 'Algorithm', level: 2, question: 'Given an array of numbers as input, generate an array that has all possible solutions for multiplying, dividing, adding and substracting all numbers with each other in the array.' },
            { id: 18, title: '', type: 'Algorithm', level: 2, question: 'How would you create all permutations of a string?' },
            { id: 19, title: '', type: 'Algorithm', level: 2, question: 'From a unsorted array, check whether there are any two numbers that will sum up to a given number.' },
            { id: 20, title: '', type: 'Algorithm', level: 2, question: 'How would you verify a word as palindrome?' },
            { id: 21, title: '', type: 'System Design', level: 0, question: 'Design an elevator.' },
            { id: 22, title: '', type: 'System Design', level: 0, question: 'Design a parking lot.' },
            { id: 23, title: '', type: 'System Design', level: 1, question: 'Design Venmo.' },
            { id: 24, title: '', type: 'System Design', level: 1, question: 'Design Mint.' },
            { id: 25, title: '', type: 'System Design', level: 1, question: 'Design a League of Legends character.' },
            { id: 26, title: '', type: 'System Design', level: 1, question: 'Design an NCAA bracket.' },
            { id: 27, title: '', type: 'System Design', level: 1, question: 'Design an NBA playoff Bracket.' },
            { id: 28, title: '', type: 'System Design', level: 2, question: 'Design a clothing factory.' },
            { id: 29, title: '', type: 'System Design', level: 2, question: 'Design a calculator that remembers previous calculations.' },
            { id: 30, title: '', type: 'System Design', level: 2, question: 'Design a Blackjack game.' },
            //Below questions Sandra added
             { id: 31, title: '', type: 'Algorithm', level: 0, question: 'There are 1000 buckets, one and only one of them contains poison, the rest are filled with water. They all look the same. If a pig drinks that poison it will die within 15 minutes. What is the minimum amount of pigs you need to figure out which bucket contains the poison within one hour.' },
            { id: 32, title: '', type: 'Algorithm', level: 0, question: 'Find the largest palindrome made from the product of two n-digit numbers.Since the result could be very large, you should return the largest palindrome mod 1337.' },
            { id: 33, title: '', type: 'Algorithm', level: 0, question: 'Write a function to find the longest common prefix string amongst an array of strings.' },
            { id: 34, title: '', type: 'System Design', level: 0, question: 'How would you design a calculator.' },
            { id: 35, title: '', type: 'System Design', level: 0, question: 'Describe the system design for a weather forecast app.' },
             { id: 36, title: '', type: 'Algorithm', level: 1, question: 'Given a string, find the length of the longest substring without repeating characters.' },
            { id: 37, title: '', type: 'Algorithm', level: 1, question: 'Given an array S of n integers, are there elements a, b, c in S such that a + b + c = 0? Find all unique triplets in the array which gives the sum of zero.' },
            { id: 38, title: '', type: 'Algorithm', level: 1, question: 'Given a digit string, return all possible letter combinations that the number could represent.' },
             { id: 39, title: '', type: 'Behavioral', level: 1, question: 'Elaborate how you solved an every day problem.' },
            { id: 40, title: '', type: 'Behavioral', level: 1, question: 'What is your greatest strength?' },
            { id: 41, title: '', type: 'Behavioral', level: 1, question: 'What is your greatest weakness?' },
            { id: 42, title: '', type: 'Behavioral', level: 1, question: 'What makes a person smart?' },
            { id: 43, title: '', type: 'Behavioral', level: 1, question: 'Explain to me what programming is.' },
             { id: 44, title: '', type: 'Algorithm', level: 2, question: 'Given an array of non-negative integers, you are initially positioned at the first index of the array.Each element in the array represents your maximum jump length at that position.Your goal is to reach the last index in the minimum number of jumps.For example:Given array A = [2,3,1,1,4]. The minimum number of jumps to reach the last index is 2. (Jump 1 step from index 0 to 1, then 3 steps to the last index.)' },
            { id: 45, title: '', type: 'Algorithm', level: 2, question: '? Matches any single character.* Matches any sequence of characters (including the empty sequence).The matching should cover the entire input string (not partial).The function prototype should be:bool isMatch(const char *s, const char *p)' },
            { id: 46, title: '', type: 'Algorithm', level: 2, question: 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it is able to trap after raining. For example,given [0,1,0,2,1,0,1,3,2,1,2,1], return 6.' },
            { id: 47, title: '', type: 'System Design', level: 2, question: 'Design a Game of thrones video game' },
            { id: 48, title: '', type: 'System Design', level: 2, question: 'How would you set up Airbnb' },
            { id: 49, title: '', type: 'System Design', level: 2, question: 'Describe the system design for an Ad-tech system' },
            { id: 50, title: '', type: 'System Design', level: 2, question: 'How would you track royalties for artists and reimburse them?' },
             { id: 51, title: '', type: 'Behavioral', level: 2, question: 'Have you every disappointed someone? How did you handle the situation' },
            { id: 52, title: '', type: 'Behavioral', level: 2, question: 'Have you ever lead a team and failed?' },
            { id: 53, title: '', type: 'Behavioral', level: 2, question: 'How would you lead a team if you were in charge of the project?' },
            { id: 54, title: '', type: 'Behavioral', level: 2, question: 'Have you ever felt desparate about being able to achieve something? What did you do to solve this?' },
            { id: 55, title: '', type: 'Behavioral', level: 2, question: 'What was the biggest loss you have encountered and how did you handle it?' },
            { id: 56, title: '', type: 'System Design', level: 0, question: 'Set up the system design for a zoo' },
            { id: 57, title: '', type: 'System Design', level: 0, question: 'How would you design a water cleaning system fro a big city' },
          ]);
        });
    });
};
